# Generated by Django 4.2.9 on 2024-01-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_app', '0002_rename_name_skill_skillname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Skillname',
            new_name='skillname',
        ),
    ]
